#!/usr/bin/env bash
# The script transfers a file from a client to a server

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
ip="$2"
username="$3"
ssh_key_path="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$ip":~/
