#!/usr/bin/env bash
# The script installs nginx in the server

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
