#!/usr/bin/env bash
#The script configures a new ubuntu server that contains a custom HTTP header

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/server_name _;/a \\\n\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
