#!/usr/bin/env bash
# A script that displays the contents of a file
# the script only displays:
# - username
# - user id
# - Home directory path of the user

while read -r line;
do
    echo "$line" | cut -d ":" -f 1,3,6
done < /etc/passwd
