#!/usr/bin/env bash
#A script that prints from 1 to 10 and prints a string.

i="0"
while [ $i -lt 10 ]
do
    i=$((i+1))

    if [ ${i,,} = 4 ]; then
        echo "bad luck"
    elif [ ${i,,} = 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
done
